Documenting QA process and guidelines
anitab-org/documentation pull request #21
Opened 2020-08-17 20:11 UTC by rpattath

Documenting QA process and guidelines with information for all repos under AnitaB.org.

This PR fixes #14

2020-08-18 20:31 UTC, isabelcosta commented on quality-assurance.md
> +1. Join #quality-assurance stream on Zulip. Tag @admins on Zulip to add you under the @qa-team tag.
```suggestion
1. Join [#quality-assurance](https://anitab-org.zulipchat.com/#narrow/stream/216325-quality-assurance) stream on Zulip. Tag @admins on Zulip to add you under the @qa-team tag.
```

2020-08-18 20:32 UTC, isabelcosta commented on quality-assurance.md
> +        * Dev Env Setup demo - [Recoreding 1](https://anitab.zoom.us/rec/share/2uNHIJT-5EVJS7PzxVrWfK0oQtS1eaa81HdP-vVcyoErlalT9Mv00cK-ZvtOiMk?startTime=1589121214000), [Recording 2](https://anitab.z
```suggestion
        * Dev Env Setup demo - [Recording 1](https://anitab.zoom.us/rec/share/2uNHIJT-5EVJS7PzxVrWfK0oQtS1eaa81HdP-vVcyoErlalT9Mv00cK-ZvtOiMk?startTime=1589121214000), [Recording 2](https://anitab.zoom.us/rec/share/2uNHIJT-5EVJS7PzxVrWfK0oQtS1eaa81HdP-vVcyoErlalT9Mv00cK-ZvtOiMk?startTime=1589121947000), [Recording 3](https://anitab.zoom.us/rec/share/2uNHIJT-5EVJS7PzxVrWfK0oQtS1eaa81HdP-vVcyoErlalT9Mv00cK-ZvtOiMk?startTime=1589122325000)
```

2020-08-20 10:52 UTC, rpattath commented
@isabelcosta I have added your comment and also included information from [here](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/test-pr-guide.md) to this doc. Please take a second look. Thanks in advance :)

2020-08-21 00:11 UTC, isabelcosta commented on quality-assurance.md
> +<h1>Pre-requisites for contributing towards Quality Assurance</h1>
```suggestion
<h1>Quality Assurance<h1>

<h2>Pre-requisites for contributing towards Quality Assurance</h2>
```

2020-08-21 00:11 UTC, isabelcosta commented on quality-assurance.md
> +<h1>Quality Assurance Guidelines</h1>
```suggestion
<h2>Quality Assurance Contribution Guidelines</h2>
```

2020-08-21 00:13 UTC, isabelcosta requested changes
This looks awesome @rpattath , I just made some comments about the hierarchy presentation for this to have 1 title, and then the subsections. Can you please add an entry to this document on the README, next to "our blog" entry. Other than that I am happy to approve

2020-08-24 14:06 UTC, siddhipandare approved these changes

2020-08-24 14:10 UTC, siddhipandare commented
Great Job @rpattath 😄 ! Thought QA was difficult to get started with, this document helps a lot to debunk that!

2020-08-24 17:50 UTC, merged

2020-08-24 17:51 UTC, isabelcosta commented
@siddhipandare thank you for reviewing this 🤗