refactor: Update fetching instructions in test PR guide
anitab-org/documentation pull request #65
Opened 2021-08-30 19:09 UTC by StephNathai

### Description
Updated the fetching instructions to test a PR in the [quality-assurance.md](https://github.com/anitab-org/documentation/blob/master/quality-assurance.md#how-to-test-a-pr) file

Fixes #53 

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
See file and display rendered version of MD file.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

2021-09-11 10:52 UTC, isabelcosta commented on quality-assurance.md
> +  git fetch upstream pull/ID/head:<branch_name>
```suggestion
  git fetch upstream pull/<id>/head:<branch_name>
```
just because above you mention `<id>`

2021-09-11 10:53 UTC, isabelcosta commented on quality-assurance.md
> +5. Alternatively, if you use the github cli, you can run the following command:
```suggestion
5. Alternatively, if you use the [GitHub CLI](https://cli.github.com/), you can run the following command:
```

2021-09-11 10:58 UTC, isabelcosta requested changes
This is great @StephNathai ! 🙌🏾 
I only left a couple of comments to make the instructions more clear and I can approve after.

Thank you for contributing!

2021-09-15 20:52 UTC, isabelcosta approved these changes
I saw myself needing this guide, so I've updated the changes I requested 😅 
Thank you for contributing @StephNathai 🙌🏾

2021-09-15 20:53 UTC, StephNathai commented
No worries! I made the changes but was waiting on an internal review before I could push it externally. Thanks!

2021-09-15 20:57 UTC, isabelcosta commented
@StephNathai what do you mean by internal review? You can push right after you do the changes :)

2021-09-15 20:57 UTC, merged

2021-09-15 20:58 UTC, StephNathai commented
@isabelcosta I'm contributing on behalf of my company so my company needs to approve all changes internally before we push them up externally

2021-09-15 21:01 UTC, isabelcosta commented
Ah ok! I just merged it 💪🏾 Thank you for your contribution! @StephNathai